### ISSUE TITLE
8.0.43前的版本没有arm64吗

### ISSUE THREAD

**Issue by BBplux** [DJB-Developer/wechat-android-history-versions#1]

**Comment by BBplux** [comment]
刚试了下7.0.22在后面加上arm46就能下64位版本，装上也确实是64位了

**Comment by DJB-Developer** [comment]
> 刚试了下7.0.22在后面加上arm46就能下64位版本，装上也确实是64位了

之前的版本都有 arm64 版本，在 8.0.43 之后貌似只有 arm64

**Comment by Arnie97** [comment]
试了下 7.0.9 之后的版本都能加 arm64 后缀：https://dldir1.qq.com/weixin/android/weixin709android1560_arm64.apk
